title: Hitchhiker's blog on software developement
author:
  name: Motaquillah Maddane
  googleplus: https://www.google.com/+MotaquillahMaddane
description: Blog about PHP(Laravel), Js(Angular), CSS & Life.
cover: /assets/images/covers/road.jpg